spring.application.name=accounts-service
server.port=8081

spring.datasource.url=jdbc:postgresql://accounts-db:5432/bank_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.packages-to-scan=accounts_service.controller