spring.application.name=ui-service
server.port=8083

spring.datasource.url=jdbc:postgresql://accounts-db:5432/bank_db
spring.datasource.username=user
spring.datasource.password=password

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always